Minio Server:
  - title: Minio Server Quickstart Guide
    link: https://raw.githubusercontent.com/minio/minio/master/README.md
    slug: minio_server_quickstart_guide
  - title: Minio Distributed Quickstart Guide 
    link: https://raw.githubusercontent.com/minio/minio/master/README.md
    slug: minio_distributed_quickstart_guide

Minio Client:
  - title: Minio Client Quickstart Guide
    link: https://raw.githubusercontent.com/minio/minio/master/README.md
    slug: minio_client_quickstart_guide
  - title: Minio Complete Client Quickstart Guide 
    link: https://raw.githubusercontent.com/minio/minio/master/README.md
    slug: minio_complete_client_quickstart_guide

Minio SDKs:
  - title: Minio SDK Guide
    link: https://raw.githubusercontent.com/minio/minio/master/README.md
    slug: minio_server_quickstart_guide
  - title: Minio API Quickstart Guide 
    link: https://raw.githubusercontent.com/minio/minio/master/README.md
    slug: minio_api_quickstart_guide

Minio Cookbook:
  - title: Minio Cookbook Guide
    link: https://raw.githubusercontent.com/minio/minio/master/README.md
    slug: minio_cookbook_guide
  - title: Minio Recipes 
    link: https://raw.githubusercontent.com/minio/minio/master/README.md
    slug: minio_recipes